### ISSUE TITLE
chore: run evaluations in Github workflow

### ISSUE THREAD

**Issue by jalling97** [defenseunicorns/leapfrogai#1076]
### Describe what should be investigated or refactored

The evaluations in `leapfrogai_evals` should be run in a Github Workflow at a semi-regular cadence. Results should also be stored as Github artifacts to begin preserving evaluation results so that performance can be tracked overtime.

### Links to any relevant code

[leapfrogai_evals](https://github.com/defenseunicorns/leapfrogai/blob/main/src/leapfrogai_evals/)

### Additional context

This will require:
- choosing a runner that can support LFAI in total
- deploying a full instance of LFAI (frog legs, no ui is likely needed)
- handling setting the API key for LFAI
- determining how to handle the Anthropic API key

**Comment by nywilken** [comment]
There might still be a need for this but it will most likely not happen in this repository. Closing the issue and marking as wontfix for now. If needed we can transfer and revisit if there is a need.
