### ISSUE TITLE
chore: add badges for cron-job or automated workflows

### ISSUE THREAD

**Issue by justinthelaw** [defenseunicorns/leapfrogai#1147]
Add README badges for workflows that run automatically (e.g., weekly, nightly, triggers) so that developers and watchers can see what is failing or passing.

**Comment by ChinoUkaegbu** [comment]
Hi, I'd like to work on this! Which of the [workflows](https://github.com/defenseunicorns/leapfrogai/actions) should I include in the README?

**Comment by justinthelaw** [comment]
@ChinoUkaegbu hello, thanks for asking!

The nightly snapshots are definitely something we want to keep track of, which I already see in your forked branch. We'll probably want these to be named "Nightly Snapshot and Upgrade Tests". We also have an End-to-End Registry1 Weekly tests that should be a badge named "Registry1 Weekly Tests". Other than that, I think those two are the near term ones.

There is one more workflow I am working on that isn't in the repository yet, called "Made for UDS" - which is a workflow that always passes but provides errors and warning on our compliance with an company Kubernetes runtime/platform called UDS. If you wait until tomorrow, it should be up and it will likely be a nightly test as well.
