### ISSUE TITLE
bug(ui): annotations no longer displaying correctly after backend change

### ISSUE THREAD

**Issue by andrewrisse** [defenseunicorns/leapfrogai#1180]
The UI's annotations no longer are being replaced by [1], [2], etc.. 

This is almost certainly due to the recent changes to annotations on the backend.

**Comment by andrewrisse** [comment]
Last I checked, the UI worked with OpenAI's annotations, so this bug may end up requiring backend changes

**Comment by gphorvath** [comment]
Solved by #1201
