### ISSUE TITLE
Context Cancellation

### ISSUE THREAD

**Issue by gerred** [defenseunicorns/leapfrogai#139]
cc @DayOfThePenguin 

One issue right now is even if gRPC gets cancelled, backend models will continue generating into the void. This can cause model servers to seemingly hang while the thread is blocked.

We need some sort of async cancellation mechanism to stop a generation.

**Comment by vanakema** [comment]
@edengebrezgi did you happen to start this ticket yet? If not, would you mind if I took over?

**Comment by justinthelaw** [comment]
@vanakema no body has started on this one yet! You can work on it if you'd like. Let me know if you have questions or want to pair on it!

**Comment by vanakema** [comment]
@justinthelaw would love to pair on it! How should we coordinate?

**Comment by justinthelaw** [comment]
Closed in favor of: #277 #279 #280
