### ISSUE TITLE
Add consistent logging throughout leapfrog

### ISSUE THREAD

**Issue by DayOfThePenguin** [defenseunicorns/leapfrogai#156]
It is currently very difficult to debug leapfrog internals, making it difficult to troubleshoot new features in development.

**Comment by DayOfThePenguin** [comment]
Root of the problem appears to be the use of grpc.WithBlock() in the grpc.Dial() calls for the huggingface and openai backends.

Google lists this as an anti-pattern for gRPC (https://github.com/grpc/grpc-go/blob/master/Documentation/anti-patterns.md). Using this will cause all grpc.Dial calls to block until connection is established instead of failing and providing an error message to users.

**Comment by justinthelaw** [comment]
Closed in favor of duplicate: #297 #685 through #688
