### ISSUE TITLE
Zarf package API Server

### ISSUE THREAD

**Issue by gphorvath** [defenseunicorns/leapfrogai#160]
- [x] Pull API Server into it's own repo
- [x] Add a `healthz` endpoint to verify the API server is running without necessarily spinning up a model
- [x] Zarf package it
- [ ] Tag a release
- [ ] Update LeapfrogAI README.md to point to the new location

**Comment by gphorvath** [comment]
https://github.com/defenseunicorns/leapfrogai_api_server

**Comment by gphorvath** [comment]
This is now for the python API server, not the go API server

**Comment by YrrepNoj** [comment]
This is complete.
https://github.com/defenseunicorns/leapfrogai/tree/main/packages/api
