### ISSUE TITLE
K3D GPU Support

### ISSUE THREAD

**Issue by gphorvath** [defenseunicorns/leapfrogai#192]
We need working K3D deployments with GPU support. Submit a PR to update "Zarf-Package-K3D-Airgap".

- [ ] Migrate away from Tommy's special K3S for GPU support.

**Comment by gphorvath** [comment]
From @YrrepNoj: https://github.com/defenseunicorns/zarf-package-k3d-airgap/pull/10

**Comment by justinthelaw** [comment]
We should not use K3D for air-gap deployments? Unless you want one that can operate in an air-gap for testing of LFAI components?

**Comment by CollectiveUnicorn** [comment]
This is finished
