### ISSUE TITLE
Expose Model Configuration

### ISSUE THREAD

**Issue by gphorvath** [defenseunicorns/leapfrogai#195]
The goal would be to provide an endpoint that could be used to gather details about the model configuration. These would be analogous to Ollamas Show Endpoint: https://github.com/ollama/ollama/blob/main/docs/api.md#show-model-information

Aspirationally, we would also update our models endpoint that lists models to include some of this information, similarly to Ollama's list endpoint: https://github.com/ollama/ollama/blob/main/docs/api.md#list-local-models

**Comment by justinthelaw** [comment]
Closed in favor of #590
