### ISSUE TITLE
Document Standing up Transcription/Summarization

### ISSUE THREAD

**Issue by gphorvath** [defenseunicorns/leapfrogai#215]
- [ ] Whisper Backend
- [ ] Mistral Backend
- [ ] API Server
- [ ] Doug Translate or Leapfrog UI depending on which becomes canon

**Comment by CollectiveUnicorn** [comment]
For the purposes of being able to have this functioning ASAP, we'll swap out Mistral for mpt-7b-chat and the Python API server with the Go one. Once we have time to test the other solutions then we'll be able to use them without time constraints weighing on the implementation.

**Comment by CollectiveUnicorn** [comment]
Fix the doug-translate Dockerfile to integrate

**Comment by CollectiveUnicorn** [comment]
Whisper needs chainguard Python image

**Comment by CollectiveUnicorn** [comment]
The text corresponding to the time spent summarizing vs transcription should be correctly displayed in doug translate.

**Comment by barronstone** [comment]
@gphorvath @CollectiveUnicorn Is this issue still relevant? I'm having a hard time understanding its intended purpose. Seems related to the scramble for transcription back in October. If this issue outdated, let's close.

**Comment by justinthelaw** [comment]
No longer relevant.
