### ISSUE TITLE
K8s Deployment Prep - Create reproducible production deployment

### ISSUE THREAD

**Issue by CollectiveUnicorn** [defenseunicorns/leapfrogai#223]
- [x] Create step by step instructions for GPU and CPU Zarf deployments in K8s
- [ ] Ensure all Zarf packages are working
- [ ] Whisper, Doug Translate, DUBBD, K3D, chat model (MPT-7B-Chat or Mistral + ctransformers), repeater (for testing)
- [x] Create AIO installation file
- [ ] Have successful repeatable procedures for deploying suite in both CPU and GPU (simulated air gap) environments
- [x] Highlight information that is needed about the environment
- [x] Easy to deploy docker solution
- [ ] Deployment metallb proxy localhost
- [ ] Deploy physical worker node
- [ ] Concurrency tests
- [ ] Full airgap test

**Comment by CollectiveUnicorn** [comment]
Confirmed `doug-translate` is working with DUBBD
Confirmed `leapfrog-api` (go api) is working with DUBBD

**Comment by CollectiveUnicorn** [comment]
Questions:
* What operating system?
* What hardware? (Provide detailed information about the Memory, CPU, GPU)
* At the time of setup, will the environment have internet access?

**Comment by CollectiveUnicorn** [comment]
WIP CPU steps - https://coda.io/d/Navy_d-MPCqR5Knp/Gato-gato-pop-os-Pop-OS-22-04-LTS-NVIDIA_surBY#_lu71C

**Comment by CollectiveUnicorn** [comment]
Stretch Goal:
-  Faster whisper CPU

**Comment by gphorvath** [comment]
Remaining work...

Ensure all Zarf packages are working:
- [ ] [K3D Local](https://github.com/defenseunicorns/uds-package-dubbd/tree/main/k3d/local)
- [ ] DUBBD
- [ ] Python-API
- [ ] Whisper
- [ ] ctransformers/Synthia
- [ ] Doug Translate

Misc Features:
- [ ] Batch Summarization within Doug Translate
- [ ] Deployment metallb proxy localhost

Testing:
- [ ]  Create step by step instructions for CPU Zarf deployments in K8s
- [ ] Have successful repeatable procedures for deploying suite in CPU environments
- [ ] Concurrency tests
- [ ] Full airgap test


Stretch Goals
- [ ] SAML

**Comment by CollectiveUnicorn** [comment]
Python API needs to have `max_new_tokens` fixed so that it properly maps to `max_tokens` otherwise responses will be truncated.

**Comment by CollectiveUnicorn** [comment]
For the concurrency test, looking at using [locust](https://locust.io/) + [pytest](https://docs.pytest.org/en/7.4.x/) + [starlette](https://www.starlette.io/testclient/) (maybe)

**Comment by CollectiveUnicorn** [comment]
Odd Zarf caching is causing packages to not be updated.

**Comment by justinthelaw** [comment]
Closed based on he most recent comment with remaining tasks completed. See https://github.com/defenseunicorns/leapfrogai-deployment for deployment instructions.
