### ISSUE TITLE
Create k8s cert for *.leapfrogai.bigbang.dev

### ISSUE THREAD

**Issue by CollectiveUnicorn** [defenseunicorns/leapfrogai#224]
When attempting to hit a user facing application (`doug-translate, leapfrog-ui`) using the host `*.leapfrogai.bigbang.dev` some browsers will fail to load due to the DUBBD cert being designed for `*.bigbang.dev`.

**Comment by YrrepNoj** [comment]
Closing this issue. Using UDS should be all we need.
