### ISSUE TITLE
Ingress Gateway in Pending state after BigBang deployment

### ISSUE THREAD

**Issue by jkraunelis** [defenseunicorns/leapfrogai#235]
The svclb-tenant-ingressgateway pod is stuck in the Pending state after deploying BigBang.

I followed the leapfrog installation instructions to install the zarf binary v0.30.1, then issues the commands

```
sudo zarf init -a amd64
sudo zarf package deploy oci://ghcr.io/defenseunicorns/packages/dubbd-k3d:0.11.0-amd64 --set APPROVED_REGISTRIES="ghcr.io/runyontr/* | ghcr.io/defenseunicorns/* | nvcr.io/nvidia/k8s/* | semitechnologies/*"
```

Nearly all pods come up okay except the svclb-tenant-ingressgateway:

```
NAME                                         READY   STATUS    RESTARTS   AGE
coredns-6799fbcd5-f592c                      1/1     Running   0          71m
local-path-provisioner-84db5d44d9-zsjn8      1/1     Running   0          71m
metrics-server-67c658944b-xkbgd              1/1     Running   0          71m
svclb-tenant-ingressgateway-33765d1d-cmgsm   0/3     Pending   0          34m
svclb-admin-ingressgateway-bdbf7330-xwwcx    3/3     Running   0          34m
```

I've attached the output of `kubectl describe po svclb-tenant-ingressgateway-33765d1d-cmgsm -n kube-system`.
[ingressgateway.txt](https://github.com/defenseunicorns/leapfrogai/files/13254501/ingressgateway.txt)

I'm running Ubuntu 22.04.3 via WSL2.

**Comment by justinthelaw** [comment]
No longer relevant.
