### ISSUE TITLE
Airgapped e2e test for LFAI components

### ISSUE THREAD

**Issue by gerred** [defenseunicorns/leapfrogai#244]
All of the e2e testing for LFAI thus far with LFAI has been done with the intent of being run in airgapped environments, but the environments haven't been actually airgapped. This is a tracking issue to make a reproducible airgapped e2e test env/suite to catch  any hidden bugs or issues before they go out to an airgapped environment for the first time.

**Comment by justinthelaw** [comment]
Closed in favor of duplicate: #707
