### ISSUE TITLE
The discord link at the bottom of the leapfrog.ai site goes to a weird discord group

### ISSUE THREAD

**Issue by AGI-CEO** [defenseunicorns/leapfrogai#254]
This is the group it goes to 
![image](https://github.com/defenseunicorns/leapfrogai/assets/29067169/6ca9b70c-548a-42cc-aacb-23a7a1f80738)

This is the link at the bottom of the page:
![image](https://github.com/defenseunicorns/leapfrogai/assets/29067169/1521904b-7f98-44c6-99b4-8dcbb1a6d03a)

**Comment by gphorvath** [comment]
Thank you for reaching out! That is managed via another repo, and we'll squash that quick. For now, please using this link to join us @AGI-CEO 
https://discord.gg/s2Ja5cmZRQ

**Comment by gphorvath** [comment]
Clear the cache, it should be fixed!

Thanks @fingermustache!
