### ISSUE TITLE
SPIKE: Determine a good way to test model backends

### ISSUE THREAD

**Issue by YrrepNoj** [defenseunicorns/leapfrogai#256]
We have several `leapfrogai-backend-...` repositories that we are maintaining that currently don't test our code as much as we would like.

Since these backends are all very similar to each other we should be able to come up with a single testing solution that can be applied to all the backend repositories in a way that requires minimal adjustment for each backend repository.

Tests for the backend will need to validate:
- [ ] Builds are able to complete (Docker and Zarf)
- [ ] Python code `leapfrogai.serve(MODEL_BACKEND())` is able to execute without any errors
- [ ] Each model is able to receive and respond to requests on its exposed OpenAI functions.
  IE)
  ```python
  # We would test that the Whisper model was succesfully responding to:
  #    - `POST /v1/audio/transcriptions`
  #    - `POST /v1/audio/translations`
  # This is because those are the functions the AudioServicer protobuf class defines
  #    - https://github.com/defenseunicorns/leapfrogai-sdk/blob/38394688e378004225ecd78691671a083a812bbd/src/leapfrogai/audio/audio_pb2_grpc.py#L29
  class Whisper(leapfrogai.AudioServicer):
  ```
- [ ] The model's Zarf package can be deployed onto k8s and used (this will be harder to test because of potential resource limitations of the runners we have easy access to)

Once we identify a testing approach we are comfortable with, we will need to incorporate the tests into all of our backend repos.

**Comment by justinthelaw** [comment]
No longer relevant.
