### ISSUE TITLE
ADR VectorDB

### ISSUE THREAD

**Issue by CollectiveUnicorn** [defenseunicorns/leapfrogai#272]
Update the ADR here: https://github.com/defenseunicorns/leapfrogai/blob/main/docs/adr/0001-vectordb-backend.md

**Comment by gphorvath** [comment]
We may promote this issue to be a general database solution for the API that supports both object storage and vector storage. Also looking for auth and other integrations.

Also day 2 ops, backups, migrations, etc.

**Comment by barronstone** [comment]
The [VectorDB ADR](https://github.com/defenseunicorns/leapfrogai/blob/main/adr/0001-vectordb-backend.md) has been superseded by the [LeapfrogAI Database ADR](https://github.com/defenseunicorns/leapfrogai/blob/main/adr/0003-database.md) selecting Supabase as our database solution.
