### ISSUE TITLE
feat(ui): cancel generation

### ISSUE THREAD

**Issue by gphorvath** [defenseunicorns/leapfrogai#278]
User Story
**As** a LFAI user
**I want** the ability to cancel an ongoing generation process and retry inferencing
**So that** I can have control over the generation process and optimize my interaction with the application

**Acceptance Criteria**
**Given** I am using chat in LFAI
**When** submit a prompt message
**Then** the "send" prompt message button changes to a "stop" response button
**And** the prompt message input remains enabled 
**And** a new prompt message can be typed but not sent

**When** I clicked the "stop" response button
**Then** the response stops immediately
**And** the response remains unfinished
**And** a response canceled Toast appears

**Additional context**
Design links
- Cancel Response [link](https://www.figma.com/file/Vaw2TCF9DPAp1msj5TWkl0/Leapfrog-AI?type=design&node-id=2860%3A60083&mode=dev&t=Hs1vpHLYaAl8NT8j-1)
- Response Canceled Toast [link](https://www.figma.com/file/Vaw2TCF9DPAp1msj5TWkl0/Leapfrog-AI?type=design&node-id=2860%3A63023&mode=dev&t=Hs1vpHLYaAl8NT8j-1)

Note: Ensure that when a response is canceled and is still the most recent response that the "regenerate" icon appears on hover. See this [story](https://github.com/defenseunicorns/leapfrogai/issues/362) for details

**Comment by gregclark-defenseunicorns** [comment]
I am breaking this up into smaller issues. Here is the first [one](https://github.com/defenseunicorns/leapfrogai/issues/362). This is for all the quick actions on Prompts and Responses.
