### ISSUE TITLE
feat: token counting endpoint

### ISSUE THREAD

**Issue by gphorvath** [defenseunicorns/leapfrogai#281]
**Type:** Feature

**Description:** Enhance the API to allow users to count tokens for text, so that prompts can be cut off at accurate points for a local LLM.

**User Story:**
As an API user, I want the ability to count tokens for a given text input, so that I can accurately truncate prompts at specific token counts when working with a local Language Model (LLM).

**Acceptance Criteria:**
- [ ] Implement a new endpoint in the API that accepts a text input and returns the token count.
- [ ] The token counting method should be consistent with the tokenization approach used by the local LLM.
- [ ] The API should handle various input lengths and provide an accurate token count for each input.
- [ ] The API response should include the original text input and the corresponding token count.
- [ ] Provide clear documentation and usage examples for the new token counting feature in the API

**Comment by CollectiveUnicorn** [comment]
Putting this on hold again, the token count will be returned by the completion API but there won't be another endpoint for the just counting just yet.
