### ISSUE TITLE
feat(api): list files

### ISSUE THREAD

**Issue by gerred** [defenseunicorns/leapfrogai#287]
## Description

Implement the OpenAI "List Files endpoint

## Acceptance Criteria

- [ ] REST endpoint that accepts a GET request with an optional [`purpose` string](https://platform.openai.com/docs/api-reference/files/object#files/object-purpose)
- [ ] Returns a list of OpenAI file objects that belong to the users organization, and filtered by `purpose` if included

**Reference:**
- <https://platform.openai.com/docs/api-reference/files/create>

**Comment by gphorvath** [comment]
Covered by https://github.com/defenseunicorns/leapfrogai/issues/312
