### ISSUE TITLE
feat(api): retrieve file content

### ISSUE THREAD

**Issue by gerred** [defenseunicorns/leapfrogai#289]
## Description

Implement the OpenAI "Retrieve File Content" endpoint

## Acceptance Criteria

- [ ] REST endpoint that accepts a GET request with a required `file_id` parameter for the file to be retrieve
- [ ] Returns the content of the specified file

**Reference:**
- <https://platform.openai.com/docs/api-reference/files/retrieve-contents>

**Comment by gphorvath** [comment]
Covered by https://github.com/defenseunicorns/leapfrogai/issues/312
