### ISSUE TITLE
feat: uds package for api database

### ISSUE THREAD

**Issue by gerred** [defenseunicorns/leapfrogai#294]
## User Story: UDS Package for API Database

**As a** DevOps engineer
**I want** to create a UDS (Unified Deployment Standard) package for the API database
**So that** the database can be easily deployed and managed in various environments

### Acceptance Criteria:
- [ ] Define the structure and contents of the UDS package for the API database
- [ ] Include all necessary database scripts, schemas, and migration files in the package
- [ ] Specify the database version and any dependencies required for the package
- [ ] Create a configuration file or template for the database connection settings
- [ ] Document the steps for deploying the database using the UDS package
- [ ] Implement a versioning scheme for the UDS package to track changes and updates
- [ ] Test the UDS package in different environments to ensure compatibility and functionality
- [ ] Automate the package creation process to ensure consistency and reproducibility
- [ ] Integrate the UDS package with the existing deployment pipeline and tools
- [ ] Provide clear instructions and documentation for using the UDS package to deploy the API database
- [ ] Ensure the UDS package follows the organization's standards and best practices for deployment artifacts

**Comment by YrrepNoj** [comment]
Closing as it has been duplicated by #345
