### ISSUE TITLE
feat(api): request/response audit logging

### ISSUE THREAD

**Issue by gerred** [defenseunicorns/leapfrogai#298]
## User Story: Request / Response Audit Logging

**As an** end user
**I want** the ability to enable audit logging for inferencing requests and responses
**So that** I can track and monitor API interactions for compliance and debugging purposes

### Acceptance Criteria:
- [ ] Implement a configuration option to enable or disable audit logging
- [ ] When audit logging is enabled, generate a unique ID for every API interaction
- [ ] Capture the following information for each API interaction:
  - [ ] Unique ID
  - [ ] Timestamp
  - [ ] User or client making the request
  - [ ] Endpoint or API method invoked
  - [ ] Request payload (including input data, parameters, and headers)
  - [ ] Response payload (including output data, status code, and headers)
- [ ] Store the captured audit logs in a secure and tamper-proof storage system
- [ ] Ensure the audit logging mechanism has minimal impact on the performance of the inferencing pipeline
- [ ] Provide a way to retrieve and query the audit logs based on different criteria (e.g., time range, user, endpoint)
- [ ] Implement proper access controls and authentication mechanisms to restrict access to the audit logs
- [ ] Ensure the audit logging system can handle high volumes of requests without causing performance degradation
- [ ] Provide documentation on how to enable and configure audit logging, as well as how to access and interpret the logged data
- [ ] Conduct thorough testing to verify the accuracy and completeness of the captured audit logs
- [ ] Ensure the audit logging system complies with relevant security and privacy regulations
- [ ] Set up automated monitoring and alerting for any anomalies or suspicious activities detected in the audit logs
- [ ] Regularly review and analyze the audit logs to identify potential issues, optimize performance, and improve the system

**Comment by justinthelaw** [comment]
Closed in favor of #688
