### ISSUE TITLE
Spike: Expose graceful failure conventions for model configuration to the API

### ISSUE THREAD

**Issue by gerred** [defenseunicorns/leapfrogai#300]
Context:

Model configuration such as model name, modalities, max context length, and other defaults are currently stringly typed across multiple services. This can lead to rapid development cycles being brittle, or production failures due to re-configuration of model backends or APIs.

Tracking issue for solutions to this problem. Some options:

- Graceful fallback to defaults
- Service discovery...?

**Comment by jalling97** [comment]
If issues related to this arise, we will address them.
