### ISSUE TITLE
feat(ui): keycloak integration

### ISSUE THREAD

**Issue by andrewrisse** [defenseunicorns/leapfrogai#306]
# Keycloak Integration

**Type:** Feature

**Description:** Integrate Keycloak auth with Supabase

**User Story:**
As a mission hero using LeapfrogAI UI, I want to login with UDS Keycloak so that I can use the app as a logged in user.

**References:**
[Keycloak & Supabase](https://supabase.com/docs/guides/auth/social-login/auth-keycloak)

**Acceptance Criteria:**
- [ ] Keycloak auth is used with Supabase to authenticate users
- [ ] Deployed in test environment
- [ ] Configuration process is documented

**Comment by YrrepNoj** [comment]
Added the blocked label. 

Blocked by #345

**Comment by YrrepNoj** [comment]
completed; resolved #380
