### ISSUE TITLE
LFAI avatar instead of Doug

### ISSUE THREAD

**Issue by gregclark-defenseunicorns** [defenseunicorns/leapfrogai#329]
### Is your feature request related to a problem? Please describe.
I want to have the LFAI avatar instead of Doug

### Describe the solution you'd like

- **Given** I submit a message prompt in LFAI
- **When** LFAI responds
- **Then** the LFAI avatar is the LFAI avatar instead of Doug

### Additional context
Design [Link](https://www.figma.com/file/Vaw2TCF9DPAp1msj5TWkl0/Leapfrog-AI?type=design&node-id=2675%3A45857&mode=dev&t=o8RCDU40Y3OHQyTR-1)

LFAI avatar is attached in both SVG and PNG (It is the same as the favicon for the app)

![Image](https://github.com/defenseunicorns/leapfrogai/assets/123974425/a554be06-6f8a-4ded-b025-8784320d1446)
![Image](https://github.com/defenseunicorns/leapfrogai/assets/123974425/84f114d7-6c85-4546-bf93-eabafbb4afaa)

**Comment by andrewrisse** [comment]
Closed with LFAIUI repo issue 17.

You can see the changes if running latest main locally, not pushing to test env right now.
