### ISSUE TITLE
Increase line spacing in message prompt and response

### ISSUE THREAD

**Issue by gregclark-defenseunicorns** [defenseunicorns/leapfrogai#330]
### Is your feature request related to a problem? Please describe.
The current message prompt and response is hard to read when it wraps due to the tight line spacing of the text.

### Describe the solution you'd like

- **Given** I am using the chat in LFAI
- **When** the message prompt or response text wraps
- **Then** the line spacing for the text is 20px

### Describe alternatives you've considered
I am not sure if the line spacing will translate from Figma design to code so try to match the spacing that is found in the design. If you have any issues just let me know and I'd be happy to pair with you.

### Additional context
Design [Link](https://www.figma.com/file/Vaw2TCF9DPAp1msj5TWkl0/Leapfrog-AI?type=design&node-id=2675%3A45857&mode=dev&t=o8RCDU40Y3OHQyTR-1)

**Comment by andrewrisse** [comment]
Closed, quick one line change was pushed to main, did not cut new release, but change can be seen if running locally
