### ISSUE TITLE
chore(docs): update the contributing and pre-commit documentation

### ISSUE THREAD

**Issue by gphorvath** [defenseunicorns/leapfrogai#332]
- [ ] Remove ADR-Tools instructions if we don't use that
- [ ] Testing section needs to be written
- [ ] Updating our documentation section should cover the website.

**Comment by justinthelaw** [comment]
There is still a mention of "Zarf project" in the `CONTRIBUTING.md`.

Also, agree that we can remove.mentions of `adr-tools` and add mentions of `pre-commit`.

We should also remove mentions of the LFAI discord.

See https://github.com/justinthelaw/repository-template/blob/main/.github/CONTRIBUTING.md as a reference.

**Comment by justinthelaw** [comment]
Bumping this to include the following:

- [ ] add pre-commit instructions
- [ ] add local testing steps (dev, docker, k8s)
- [ ] release-please (dev and official) release workflows
- [ ] PRs and commit etiquette

Use this as an example starting point: https://github.com/justinthelaw/uds-rke2/blob/main/.github/CONTRIBUTING.md
