### ISSUE TITLE
feat(backend): Create Supabase Zarf configuration

### ISSUE THREAD

**Issue by andrewrisse** [defenseunicorns/leapfrogai#345]
Deploy Supabase into leapfrog-04 and leapfrog-demo.

Given I am a Leapfrog team member, when I deploy LeapfrogAI systems I can connect them to Supabase in our clusters instead of a cloud SAAS offering.

- [x] Get the bitnami or community chart deployed locally
- [ ]  Determine what customizations (chart variables and UDS overrides) are needed for our use case
    - [ ] Auth
    - [ ] Ingress (istio) ->  uds-operator Package CRD
    - [ ] Pepr compliance
    - [ ] Note: potentially split this into a new issue for AWS provided backing store (s3) vs HA in-cluster backing store
- [x] Create Zarf package config that deploys said chart
- [ ] Update uds-bundle.yaml to include the supabase package
- [ ] Create new issues for work needed to utilize this package with our UI/Rag/etc

### Additional context
Official docs: https://supabase.com/docs/guides/self-hosting
Community Supported: https://supabase.com/docs/guides/self-hosting#community-supported
Reference for running with Docker: https://supabase.com/docs/guides/self-hosting/docker#running-supabase

**Comment by CollectiveUnicorn** [comment]
Draft PR can be found here: https://github.com/defenseunicorns/leapfrogai/pull/380

**Comment by YrrepNoj** [comment]
completed; resolved #380
