### ISSUE TITLE
feat(ui): sidenav search

### ISSUE THREAD

**Issue by andrewrisse** [defenseunicorns/leapfrogai#353]
# Sidenav Search

**Type:** Feature

**Description:** Implement search functionality for Sidenav conversations

**User Story:**
As a mission hero using LeapfrogAI UI, I want to search through my conversations so that I can find previous AI responses

**References:**

**Acceptance Criteria:**
- [ ] Search filters conversations while typing
- [ ] Search correctly filters conversations to only conversations with matching text

**Comment by gregclark-defenseunicorns** [comment]
Checked the branch and it passes design review
