### ISSUE TITLE
spike: Investigate locking down the API

### ISSUE THREAD

**Issue by YrrepNoj** [defenseunicorns/leapfrogai#358]
### Describe what should be investigated or refactored
Right now, our API is publicly available at `leapfrogai-api.DOMAIN`.

There are several potential paths forward that we need to investigate:
- Do not expose the API publicly. Only use it through our UI or other managed tools.
- Use [supabase to secure the api](https://supabase.com/docs/guides/api/securing-your-api)
- Use keycloak to try to limit access to the API

**Comment by CollectiveUnicorn** [comment]
This is resolved with the API keys
