### ISSUE TITLE
chore(ui): change sidenav date sorting

### ISSUE THREAD

**Issue by andrewrisse** [defenseunicorns/leapfrogai#360]
Change sidenav date sorting to not use [month] - [year] method.

**Type:** Chore

**Description:** Currently, conversations that are from a previous year, but not yet in the "old" category are annotated by [month] - [year]. Remove this and sort by month ascending. 
Ex.
Today
Yesterday
This Month
January
December
November

Also, conversations that make it into the 'old' category currently do not get sorted by date once placed in "old". Fix this bug.

Additionally, categories that don't have any conversations in them should not be displayed.

**User Story:**
As a mission hero, I want to see my conversations sorted by date so that I can find old conversations easily.

**Acceptance Criteria:**
- [ ] Dates are sorted IAW description above
- [ ] Conversations in "old" category are sorted by dates properly
- [ ] Categories with no dates do not display

**Comment by gregclark-defenseunicorns** [comment]
Checked the branch and it passes design review
