### ISSUE TITLE
feat(ui): import export conversations

### ISSUE THREAD

**Issue by andrewrisse** [defenseunicorns/leapfrogai#381]
### User Story

**As a** mission hero 
**I want** to export and import my conversation history 
**So that** my co-worker can use them

### Acceptance Criteria

**Given** a mission hero clicks the export data button
**When** the file downloads automatically
**Then** it has all the conversations and messages

**Given** a mission hero clicks the import data button
**When** json files are able to be uploaded
**Then** the conversations are imported

### Additional context
Imports should not overwrite existing conversations, just duplicate them if they are the same.
Only JSON files should be able to be uploaded.
Validate the JSON file is in the proper format.
Notify the user of errors.

**Comment by gregclark-defenseunicorns** [comment]
Checked the branch and it passes design review
