### ISSUE TITLE
chore: add headless UI tests to PR workflow

### ISSUE THREAD

**Issue by gerred** [defenseunicorns/leapfrogai#402]
### Describe what should be investigated or refactored
Currently, UI tests are part of Husky. They should be part of a workflow check.

**Comment by barronstone** [comment]
This issue no longer needed; addressed by [Issue 557](https://github.com/defenseunicorns/leapfrogai/issues/557)

**Comment by barronstone** [comment]
This issue no longer needed; addressed by [Issue 557](https://github.com/defenseunicorns/leapfrogai/issues/557)
