### ISSUE TITLE
ci: Prevent e2e tests from running on draft PRs

### ISSUE THREAD

**Issue by YrrepNoj** [defenseunicorns/leapfrogai#410]
### Describe what should be investigated or refactored
We currently run our e2e tests on all PRs, including draft PRs that are probably not ready for review. Since we have a limited number of runners in our pool to utilize, we should try to save them for when know they would be useful.

**Comment by gphorvath** [comment]
Resolved here: 
https://github.com/defenseunicorns/leapfrogai/pull/429
