### ISSUE TITLE
feat: utilize keycloak for authing to LFAI things

### ISSUE THREAD

**Issue by YrrepNoj** [defenseunicorns/leapfrogai#412]
Authorizing calls to the API by validating the credentials provided by keycloak and sending that information in the 'session token' passed to the backend. 

NOTE: Using authservice might change this approach.

**Comment by YrrepNoj** [comment]
CLOSING AS DUPLICATE OF #483

**Comment by barronstone** [comment]
Addressed by [https://github.com/defenseunicorns/leapfrogai/pull/533](https://github.com/defenseunicorns/leapfrogai/pull/533)
