### ISSUE TITLE
feat(api): API_KEY authentication

### ISSUE THREAD

**Issue by YrrepNoj** [defenseunicorns/leapfrogai#413]
Mimic this: 
```
    -H "Authorization: Bearer $OPENAI_API_KEY" \
```

The API server logic should validate that a key has been provided, the key is valid (and has proper scopes) for what resources/actions the request is making.

This story involves generating API_KEYS that are created by the authenticated keycloak identity.

**Comment by gphorvath** [comment]
This issue was actually resolved by https://github.com/defenseunicorns/leapfrogai/pull/658

**Comment by nywilken** [comment]
Thanks @gphorvath
