### ISSUE TITLE
feat(api): Vector Stores endpoints

### ISSUE THREAD

**Issue by gphorvath** [defenseunicorns/leapfrogai#421]
### User Story

**As a** LeapfrogAI Developer 
**I want** an OpenAI compliant Vector Stores API
**So that** I can interact with the vector store via the API

### Acceptance Criteria

Implement and test the following endpoints:
- [ ] Create vector store
- [ ] List vector store
- [ ] Retrieve vector store
- [ ] Modify vector store
- [ ] Delete vector store

### Additional context
- https://platform.openai.com/docs/api-reference/vector-stores

**Comment by CollectiveUnicorn** [comment]
Supabase's Postgres instance will likely need to have pgvector enabled in the migrations: https://supabase.com/docs/guides/database/extensions/pgvector
