### ISSUE TITLE
Automatically pull the secrets out of Keycloak and convert them into K8s secrets

### ISSUE THREAD

**Issue by CollectiveUnicorn** [defenseunicorns/leapfrogai#441]
### Describe what should be investigated or refactored
As a LeapfrogAI dev, I need be able to deploy Supabase with Auth without a manual step to create a k8s secret. At present Supabase requires a Keycloak client secret. This secret is manually converted into a k8s secret. This needs to be automated so that there's not a manual step interceding in the deployment process. The client secret needs to be taken out of Keycloak and put in the Supabase Auth environment variable `GOTRUE_EXTERNAL_KEYCLOAK_SECRET`.

### Additional context
Some investigation has been done into using [External Secrets](https://external-secrets.io/) to make an API call to keycloak and pull out the client secret and convert it into a k8s secret where it can be accessed by automation. This requires a secret with keycloak creds, a webhook secrets generator, a secret store, and an external secret.

**Comment by CollectiveUnicorn** [comment]
Blocked by https://github.com/defenseunicorns/leapfrogai/issues/345

**Comment by YrrepNoj** [comment]
completed, resolved #380
