### ISSUE TITLE
Automatically create lfaiui configs in Keycloak

### ISSUE THREAD

**Issue by CollectiveUnicorn** [defenseunicorns/leapfrogai#448]
### Describe what should be investigated or refactored
When deploying lfaiui with Auth Keycloak needs to be configured. This configuration is manual at present. The configuration should be automated at Zarf/UDS deploy time to eliminate the need for manual configuration.

Necessary Setup
* In the `uds` realm, under client the `lfaiui` client needs to be created.
* The `lfaiui` client needs to have the following configs:
  * For `Valid redirect URIs` and `Web origins`:
    * http://localhost:5173/auth/callback
    * https://supabase-kong.uds.dev/auth/v1/callback
    * http://127.0.0.1:54321/auth/v1/callback
    * https://lfaiui.uds.dev/
    > Note - the localhost and 127.0.0.1 addresses are for allowing local versions of lfaiui to authenticate with a deployed instance of Keycloak on UDS. You would not need these for a production setup
  * `Client authentication` on
  * `Authentication flow` `Standard flow` and `Direct access grants`
  * `Standard flow` and `Direct access grants` enabled
  * `Front channel logout` and `Backchannel logout session required` on
  * Under `Client Scopes` `lfaiui-dedicated` needs to be created with a `none` `Assigned type`
  * Under `Advanced` `Open ID Connect Compatibility Modes` `Use refresh tokens` should be enabled

> Many of these settings are configured default with UDS Keycloak. The manual steps we had to accomplish were:
* turn on client authentication
* add the valid redirect urls and web origins
* copy the Client Secret from the lfaiui client in Keycloak and create a k8s secret for Supabase

They keycloak admin dashboard can be accessed at: https://keycloak.admin.uds.dev/
The admin username and password can be found in a Kubernetes secret called keycloak-admin

### Additional context
<img src="https://github.com/defenseunicorns/leapfrogai/assets/115658935/fa3099b5-546e-42f8-95b5-f129cfb0c66b" width="250" height="250">
<img src="https://github.com/defenseunicorns/leapfrogai/assets/115658935/6bc5cb27-408c-4634-b55e-84bdaa24218d" width="250" height="250">
<img src="https://github.com/defenseunicorns/leapfrogai/assets/115658935/700db2fc-46ce-412f-bfca-3c998687256a" width="250" height="250">
<img src="https://github.com/defenseunicorns/leapfrogai/assets/115658935/c20687ca-3064-43ef-835a-f2ff95c9d46b" width="250" height="250">
<img src="https://github.com/defenseunicorns/leapfrogai/assets/115658935/7cac9802-1ffa-4664-871a-794c066782da" width="250" height="250">
<img src="https://github.com/defenseunicorns/leapfrogai/assets/115658935/80c0ffed-3509-4738-8ca4-d82a0bfc8cea" width="250" height="250">
<img src="https://github.com/defenseunicorns/leapfrogai/assets/115658935/391b6700-830c-44b4-8bca-a5bb361bcb72" width="250" height="250">
<img src="https://github.com/defenseunicorns/leapfrogai/assets/115658935/be583105-d4b8-42dd-9855-c9dcf555d529" width="250" height="250">
<img src="https://github.com/defenseunicorns/leapfrogai/assets/115658935/f2547aa9-d599-4463-a9f8-d4f849bf3919" width="250" height="250">
<img src="https://github.com/defenseunicorns/leapfrogai/assets/115658935/99783afa-235a-4c86-809f-85681d92fc77" width="250" height="250">
<img src="https://github.com/defenseunicorns/leapfrogai/assets/115658935/e6c9ba42-9712-4328-9bf0-fc17d37a4005" width="250" height="250">
<img src="https://github.com/defenseunicorns/leapfrogai/assets/115658935/feca4962-4426-4ea0-a71a-62417f2efd9f" width="250" height="250">
<img src="https://github.com/defenseunicorns/leapfrogai/assets/115658935/1bddfbf8-bf6f-46d6-b0f2-6eeb2def087c" width="250" height="250">
<img src="https://github.com/defenseunicorns/leapfrogai/assets/115658935/87966a50-be02-467e-a0ff-35cb03248cd4" width="250" height="250">
<img src="https://github.com/defenseunicorns/leapfrogai/assets/115658935/ff084748-832c-4bc7-b66f-79b5f3c4b5b6" width="250" height="250">

**Comment by CollectiveUnicorn** [comment]
Blocked by #345

**Comment by YrrepNoj** [comment]
completed; resolved #380
