### ISSUE TITLE
Supabase - Add better cleanup

### ISSUE THREAD

**Issue by CollectiveUnicorn** [defenseunicorns/leapfrogai#479]
### Describe what should be investigated or refactored
Identify Supabase dependencies that need to be cleaned up in the cluster when removing Supabase and remove the `Cleanup Supabase` step for the Supabase job in the e2e workflow in favor of using `actions.onRemove.before|after` in Supabase's zarf.yaml. 

### Additional context
https://github.com/defenseunicorns/leapfrogai/pull/380/files/f9be536e7fdfa0f8a988b4de9dc97857ec4c2a88#r1589300916

**Comment by CollectiveUnicorn** [comment]
Blocked by https://github.com/defenseunicorns/leapfrogai/pull/380

**Comment by YrrepNoj** [comment]
Closing as duplicate to #454
