### ISSUE TITLE
feat(API): Add authentication

### ISSUE THREAD

**Issue by gphorvath** [defenseunicorns/leapfrogai#483]
### User Story

**As a** LeapfrogAI user
**I want** authentication for LeapfrogAI API
**So that** my data is secure and separated.

### Additional context

The [OpenAI spec uses API keys](https://platform.openai.com/docs/api-reference/making-requests) for the user.

Idea: Have the UI lookup the User's API Key in Supabase and pass it to the API so the API spec remains compliant with OpenAI.

**Comment by YrrepNoj** [comment]
When does the API key get created?
 - The [first time user logs into](https://github.com/defenseunicorns/leapfrogai/blob/7ba0e530321c6a4c54cf778adff8e08400d16279/src/leapfrogai_ui/supabase/migrations/20240513155910_all_migrations.sql#L112) `ai.xxx.xxx` generate the key
 
- [ ] Update [profile](https://github.com/defenseunicorns/leapfrogai/blob/7ba0e530321c6a4c54cf778adff8e08400d16279/src/leapfrogai_ui/supabase/migrations/20240513155910_all_migrations.sql#L19) table in the database to store the api-key

- [ ] consider using jwt/session token to add more security by making the calls expire and be more transactionally validated
   - In this case, the key can be the JWT token
