### ISSUE TITLE
Supabase - Migration version control

### ISSUE THREAD

**Issue by CollectiveUnicorn** [defenseunicorns/leapfrogai#486]
### Describe what should be investigated or refactored
Investigate postgres migration version control tools and set it up for our Supabase migrations.

### Additional context
Our migrations currently run every time the Postgres container starts up. To prevent the need for being extremely cautious when writing migrations we should be using some version control that will keep track of what migrations have already been applied to the database and only run newly added migrations.

Examples of some solutions:
- Supabase CLI
  - Ensure that this actually does version control (stores and reconciles previously run migrations) and doesn't just run the entire suite of migrations every time.
- Flyway
- Liquibase: https://www.liquibase.com/
- Bytebase

**Comment by CollectiveUnicorn** [comment]
Blocked by #380

**Comment by CollectiveUnicorn** [comment]
Consider that other environments may already have a schema deployed with data in it prior to this issue.

**Comment by gphorvath** [comment]
@CollectiveUnicorn here is another: 

https://github.com/sqitchers/sqitch

**Comment by gphorvath** [comment]
https://www.liquibase.com/

**Comment by YrrepNoj** [comment]
Resolved by #570
