### ISSUE TITLE
Determine why vllm has caching issues in pipeline

### ISSUE THREAD

**Issue by CollectiveUnicorn** [defenseunicorns/leapfrogai#504]
### Environment
Device and OS: Pipeline

### Steps to reproduce
1. Run the e2e tests and wait for it to fail

### Expected result
The build-vllm step to complete successfully

### Actual Result
The build-vllm has a caching error

### Visual Proof (screenshots, videos, text, etc)

https://github.com/defenseunicorns/leapfrogai/actions/runs/9069750197/job/24921856216?pr=503#step:21:412

![image (8)](https://github.com/defenseunicorns/leapfrogai/assets/115658935/1d16e6af-adf0-41e2-ae20-23918c74d347)

### Severity/Priority
Medium

### Additional Context
Happens inconsistently, may need to run multiple times

**Comment by justinthelaw** [comment]
No longer relevant
