### ISSUE TITLE
feat(ui) Assistant selection in Chat

### ISSUE THREAD

**Issue by gregclark-defenseunicorns** [defenseunicorns/leapfrogai#506]
### User Story

**As a** LFAI user
**I want** select an assistant for chat
**So that** I can received cater responses based on the assistant selected

### Acceptance Criteria

**Given** I am on the chat page of LFAI
**When** click on the Assistant Drop Down
**Then** I see a list of Assistants from my Assistants Management page
**And** my Assistant I have selected is in the selected state
**And** an option to Manage assistants

**When** I select a different Assistant from the list
**Then** the Drop Down closes
**And** the selected Assistant switches to the newly select Assistant

**When** I click on Manage assistants
**Then** I am navigated to the Assistants Management page

______

**Given** I have an Assistant selected in the chat page
**When** I submit a prompt message
**Then** the response uses the selected assistant to generate the response message
**And** the response avatar is the avatar associated with the selected assistant

______

**Given**  I am on the chat page of LFAI
**Then** I see the title "You" on all prompt messages in the chat thread
**And** I see the title of the respective assistant for all response messages

**Note:** Response avatar can be different in the same chat thread. If this is an issue please let me know and we can brainstorm an alternative solution.

### Additional context
Designs:
- [Closed Assistant Drop Down](https://www.figma.com/file/Vaw2TCF9DPAp1msj5TWkl0/Leapfrog-AI?type=design&node-id=2675%3A45857&mode=dev&t=lkGeym6RpA4Vp5ER-1)
- [Open Assistant Drop Down](https://www.figma.com/file/Vaw2TCF9DPAp1msj5TWkl0/Leapfrog-AI?type=design&node-id=2687%3A105813&mode=dev&t=lkGeym6RpA4Vp5ER-1)

**Comment by andrewrisse** [comment]
closed by PR #599
