### ISSUE TITLE
chore(ui) - ensure all carbon global style overrides are protected within classes

### ISSUE THREAD

**Issue by andrewrisse** [defenseunicorns/leapfrogai#525]
There are several global carbon component style overrides that are not wrapped by parent style containers. This means the global overrides are affecting the entire app, and are not just scoped to their individual components. This can cause confusing style bugs when building new components.

Wrap these overrides with a parent class so they are not true global overrides (just global overrides for the underlying carbon component).

Proper example:
```
  .inner-side-nav-container {
    height: 100%;

    :global(.bx--overflow-menu) {
      width: 16px;
      height: 32px;
      z-index: 1;
    }

    :global(.bx--overflow-menu-options) {
      left: 20px !important;
    }
  }
```

**Comment by CollectiveUnicorn** [comment]
Deleting carbon
