### ISSUE TITLE
feat(ui) Chat history import loading component

### ISSUE THREAD

**Issue by gregclark-defenseunicorns** [defenseunicorns/leapfrogai#541]
### User Story

**As a** LFAI user
**I want** see progress of a chat history import
**So that** I have direct feedback on the progress of my import

### Acceptance Criteria

**Given** I am importing a chat history
**When** the import is loading
**Then** I see the loading component below the search field in the left panel with the text "Chat history import"
**If** the import is successful
**Then** I see the complete state of the loading component appear for 1.5 seconds
**If** the import fails
**Then** I see the error state of the loading component appear for 1.5 seconds

### Additional context
Designs:
- [In Progress Import](https://www.figma.com/file/Vaw2TCF9DPAp1msj5TWkl0/Leapfrog-AI?type=design&node-id=3328%3A244035&mode=dev&t=KyJtC2uDrDZqHD2o-1)
- [Successful Import](https://www.figma.com/file/Vaw2TCF9DPAp1msj5TWkl0/Leapfrog-AI?type=design&node-id=2742%3A39503&mode=dev&t=KyJtC2uDrDZqHD2o-1)
- [Failed Import](https://www.figma.com/file/Vaw2TCF9DPAp1msj5TWkl0/Leapfrog-AI?type=design&node-id=2742%3A43261&mode=dev&t=KyJtC2uDrDZqHD2o-1)

**Comment by andrewrisse** [comment]
@gregclark-defenseunicorns I'd like to close this since we do a loading spinner on the import chat history button now instead

**Comment by andrewrisse** [comment]
implemented as spinner on import button instead, included with flowbite refactor
