### ISSUE TITLE
feat(ui): code block rendering

### ISSUE THREAD

**Issue by justinthelaw** [defenseunicorns/leapfrogai#556]
### User Story

**As a** developer using LeapfrogAI's chat UI for code generation and programming questions
**I want** the chat UI responses with code in a particular language to be rendered as a code block with the correct syntax highlighting
**So that** I can easily comprehend, critique, and copy the generated code

### Acceptance Criteria

**Given** a coding-related prompt leads to code generation by the AI backend
**When** this code block is generated using markdown syntax
**Then** a code block with proper syntax highlighting, and a copy button, are rendered in-line on the chat UI

- [ ] Code blocks for all general programming languages, with correct syntax highlighting
- [ ] Code blocks with a copy button that preserves all code properties (tabbing/spacing, special characters, etc.)
- [ ] Follow ChatGPTs format with displaying program language at the top of the block as well as a copy icon action (See screenshot below)

### Describe alternatives you've considered

N/A

### Additional context
Example of current, undesired behavior:
[Screenshot from 2024-05-23 10-34-50](https://github.com/defenseunicorns/leapfrogai/assets/81255462/de4a7477-88c5-4bc5-be38-787d0b5e1751)

ChatGPT Screenshot:
![Screenshot 2024-07-03 at 12 28 28 PM](https://github.com/defenseunicorns/leapfrogai/assets/123974425/eddba228-7a2a-45e1-a402-c339fae1113b)

**Comment by gregclark-defenseunicorns** [comment]
@andrewrisse Since @justinthelaw already wrote this issue up it will replace the [placeholder](https://github.com/defenseunicorns/leapfrogai/issues/674) issue I made
