### ISSUE TITLE
feat(API) Long Lived API Keys

### ISSUE THREAD

**Issue by CollectiveUnicorn** [defenseunicorns/leapfrogai#561]
### User Story

**As a** User of an external tool (continue.dev, Mattermost, etc...)
**I want** To be able to generate and use API keys to authenticate calls to the API. These API keys should never expire, but have a way to be revoked.
**So that** I can use external tools and authenticate without having to refresh an `access_token` every hour.

### Acceptance Criteria

**Given** I make an authenticated call to the LeapfrogAI api to create a long lived API key.
**When** I use the key in the Authorization header to make calls to the API.
**Then** authentication and RLS works as it does when I use a Supabase JWT access token.

### Describe alternatives you've considered
* Maintaining and updating the session on the backend within the API using the JWT `refresh_token`.
  * It is unusual to require the user to send the `refresh_token` over alongside the `access_token` and has high overhead with maintaining a long lived session. Additionally the system would need to be able to recover if the API goes down, so this would require persistence.
* Generating long-lived keys via Supabase.
  * This is not supported, the `access_tokens` have a limited lifespan and the expiry cannot be changed per key, it is set application wide.
* Create API keys
  * https://gist.github.com/j4w8n/25d233194877f69c1cbf211de729afb2
  * https://github.com/orgs/supabase/discussions/12328
  * https://github.com/supabase/supabase/issues/7186
  * https://gist.github.com/FelixZY/0aef530690458b381b8100afa19202c8
  * https://database.dev/martindonadieu/supabase_auth_apikey

### Additional context
* Its probably fine to assume that the user has access to the UI and can use the UI's auth session to generate, view, and update these keys.

**Comment by barronstone** [comment]
I opened a related issue for [Session Authentication via API](https://github.com/defenseunicorns/leapfrogai/issues/576) based on my understanding of things from our discussion this morning. We'll need to consider if it makes sense to implement session authentication, long-lived keys, or both. (Considered by people smarter than me.)

**Comment by CollectiveUnicorn** [comment]
@barronstone To clarify, these issues as written now are the same. Supabase has no way to offer anything other than temporary session tokens (the current lifetime is set to 1 hour, but you can configure it Supabase wide to be longer or shorter). So any solution that generates keys that won't be expiring will have to use a secure call to the LeapfrogAI API for the request to generate new tokens. So there might need to be more specific details that explain how these two are different.
