### ISSUE TITLE
chore(docs): Add Supabase instructions to top-level README

### ISSUE THREAD

**Issue by CollectiveUnicorn** [defenseunicorns/leapfrogai#579]
### Describe what should be investigated or refactored
The top-level README has no instructions related to setting up, running, or testing Supabase. We should update the README such that a user can setup and run Supabase for dev/testing.

**Comment by justinthelaw** [comment]
This will be moved into the supabase directory, and referenced by the src/leapfrogai_api directory. No dev/testing will be directly in the root README, only quickstart and pointers.
