### ISSUE TITLE
feat(api): Scheduled Vector Store Expiration

### ISSUE THREAD

**Issue by gphorvath** [defenseunicorns/leapfrogai#593]
### User Story

**As a** API User 
**I want** automated expiration of Vector Stores  
**So that** I can save space and gracefully relay the expiration status of a vector store to the end user.

### Acceptance Criteria

**Given a** Vector Store entry in the database
**When the** Vector Store is expired
**Then the** entry is automatically deleted by a scheduled Postgres function

**Given a** user querying an expired Vector Store
**When the** query is executed
**Then the** system gracefully informs the user of the expiration and handles the query appropriately

### Additional context
Currently Vector Store expiration is checked on querying some endpoints and if expired the vector store is deleted. To save space, we should automate this in some sort of Postgres function that runs on an interval and we should also check to make sure we gracefully fail whenever a user tries to query an expired vector store.

**Comment by CollectiveUnicorn** [comment]
Does the vector store expiring affect the assistants?

**Comment by CollectiveUnicorn** [comment]
The vector store cascade deletes but this does not affect the references on the assistant as there are no connections between the tables that would cause the cascade to reach the assistant. When the assistant is queries using the vector store after deletion it appears as though it does not affect output or cause an error.
