### ISSUE TITLE
spike(ui) Navigate back to most recent chat thread

### ISSUE THREAD

**Issue by gregclark-defenseunicorns** [defenseunicorns/leapfrogai#596]
This spike is to research the possibility of navigating the user back to the most recent chat thread when they navigate back to the chat page of LFAI. If there is ever not a most recent chat thread to navigate to then a new chat thread will be the default.

Spend only a couple hours on this to see if it is feasible. If not, no big deal, we will then figure an alternate solution

**Comment by andrewrisse** [comment]
closed by #615
