### ISSUE TITLE
feat(api) Messages Include Annotation Data

### ISSUE THREAD

**Issue by barronstone** [defenseunicorns/leapfrogai#605]
### User Story

**As an** end user using LeapfrogAI to "chat with my docs"
**I want** to see annotations with my RAG responses
**So that** I can attribute the source of the generated response

### Acceptance Criteria

**Given** an Assistant exists with one or more files for RAG  
**When** one or more of those files is used to generate a response
**Then** the returned Message should include `file_citation` and `file_path` annotation information

### Additional context
- [API Documentation for `messages`](https://platform.openai.com/docs/api-reference/messages)
- [Description of Message annotations](https://platform.openai.com/docs/assistants/how-it-works/managing-threads-and-messages)

**Comment by gphorvath** [comment]
The annotations are implemented, however they are always present instead of only including them when the source was actually used in the response:

![image](https://github.com/defenseunicorns/leapfrogai/assets/17520730/995a9e6a-5d8a-4440-8816-fefdfbd88d21)

**Comment by CollectiveUnicorn** [comment]
Handled by https://github.com/defenseunicorns/leapfrogai/issues/669
