### ISSUE TITLE
chore(docs): update developer and installation docs

### ISSUE THREAD

**Issue by unicorn-kp** [defenseunicorns/leapfrogai#610]
Quick Start guide should be updated from `uds deploy k3d-core-slim-dev:0.18.0` to `uds deploy k3d-core-slim-dev:0.22.0` otherwise Supabase deployment fails.

**Comment by justinthelaw** [comment]
Please note that these steps only allow you to access basic AI chat through our LeapfrogAI UI in developer mode, using CPU-only.

**General Reminders**
* Recommended specifications for a "small development deployment":
  * CPU-only
     * 8 CPU cores
     * 32 Gb RAM
  * GPU
     * CPU-only specs
     * NVIDIA RTX 4090
* Perform all commands as root by opening a sudo shell:  `sudo su`
* If doing a fresh install, run the following commands in the context in which you had previously installed UDS:

```bash
k3d cluster delete uds  # kills a running uds cluster
uds zarf tools clear-cache # clears the Zarf tool cache
rm -rf ~/.uds-cache # clears the UDS cache
docker system prune -a -f # removes all hanging containers and images
docker volume prune -f # removes all hanging container volumes
```

**General Debugging**
* We use a tool called K9s, which is vendored by the Zarf tool, which in turn is vendored by UDS CLI. To access the Kubernetes monitoring/debugging tool, execute:  `uds zarf tools monitor`
  * In K9s, you can use arrow keys to navigate, "enter" to dive into a resource, "esc" to back out of a resource, ":" (colon) to type and goto a specific resource (e.g., pods, deployments, etc.), "/" (slash) to search within the current window (press "n" to scroll to next result, and "enter" or "esc" to complete search)
  * If you want to learn more, go to https://k9scli.io/
* UDS also vendors Kubectl, and it can be used like this: `uds zarf tools kubectl [YOUR KUBECTL COMMAND]`
  * If you want to learn more, go to: https://kubernetes.io/docs/reference/kubectl/quick-reference/
* UDS Core Slim Dev (the version you are using for development deployment) is K3s in Docker, or K3D for short. 
  * If you want to learn more, go to: https://k3d.io/v5.6.3/usage/commands/k3d/

**Deploy UDS Core**
1. Ensure that UDS Core prerequisites are fulfilled: https://github.com/defenseunicorns/uds-core#prerequisites
2. Install the latest minor version of UDS Core with the following command: `uds deploy k3d-core-slim-dev:0.22.0`
3. Everything should install without any issues on your Ubuntu 20.04 or 22.04 OS

**Deploy LeapfrogAI**
1. Build and deploy the LeapfrogAI 0.7.2 (latest) CPU bundle:
```bash 
cd uds-bundles/dev/cpu
uds create .
uds deploy uds-bundle-leapfrogai*.tar.zst --confirm
```

**Access LeapfrogAI UI via KeyCloak SSO**
1. Connect to the KeyCloak admin panel
  a. Run the following to get a port-forwarded tunnel:  `uds zarf connect keycloak`
  b. Go to the resulting localhost URL and create an admin account
2. Go to ai.uds.dev and press "Login using SSO"
3. Register a new user by pressing "Register Here"
4. Fill-in all of the information
  a. The bot detection requires you to scroll and click around in a natural way, so if the Register button is not activated despite correct information, try moving around the page until the bot detection says 100% verified
6. Using an authenticator, follow the MFA steps
7. Go to sso.uds.dev 
  a. Login using the admin account you created earlier
8. Approve the newly registered user
  a. Click on the hamburger menu in the top left to open/close the sidebar
  b. Go to the dropdown that likely says "Keycloak" and switch to the "uds" context
  c. Click "Users" in the sidebar
  d. Click on the newly registered user's username
  e. Go to the "Email Verified" switch and toggle it to be "Yes"
  f. Scroll to the bottom and press "Save"
9. Go back to ai.uds.dev and login as the registered user
10. You should now have the AI chat interface in front of you
  a. Only general AI chat works
  b. Assistants, RAG, etc. will not be functional in this developer install and version
