### ISSUE TITLE
bug(ui) Profile does not update for assistant

### ISSUE THREAD

**Issue by gregclark-defenseunicorns** [defenseunicorns/leapfrogai#614]
### Environment
Device and OS: MacBook Pro
App/package versions: LFAI main
Kubernetes distro being used:
Other:

### Steps to reproduce
1. Edit an assistant profile
2. Change the profile image
3. Navigate away from Edit Assistant page
4. Allows you to navigate without the Unsaved Changes modal appearing
5. Profile image is not updated

### Expected result
**IF** the profile image is changed for an assistant and the user navigates away from the Edit Assistant page without clicking Save or Cancel
**THEN** the Unsaved Changes modal appears

### Actual Result
**IF** the profile image is changed for an assistant and the user navigates away from the Edit Assistant page without clicking Save or Cancel
**THEN** the Unsaved Changes modal does not appear and the user is navigated away from Edit Assistant page and the profile image is not updated

### Severity/Priority
Low

### Additional Context
Add any other context or screenshots about the technical debt here.

**Comment by andrewrisse** [comment]
closed by #776
