### ISSUE TITLE
feat(backend) Implement Queue for computationally expensive tasks

### ISSUE THREAD

**Issue by barronstone** [defenseunicorns/leapfrogai#626]
### User Story

**As a** LeapfrogAI end user
**I want** to upload multiple documents at once
**So that** so that I can create Assistants to "chat with my docs"

**As a** LeapfrogAI end user
**I want** to upload multiple audio and/or video files at once
**So that** so that I can transcribe and/or translate the recording

### Acceptance Criteria

**Given** the user has multiple files to upload for RAG and/or transcription/translation
**When** the user uploads those files via the UI or API
**Then** the files are queued up for sequential in-processing

**Given** multiple user have files to upload for RAG and/or transcription/translation
**When** those users concurrently upload their files via the UI or API
**Then** the files are queued up for sequential in-processing

### Describe alternatives you've considered
(optional) A clear and concise description of any alternative solutions or features you've considered.

### Additional context
In addition to queuing up multiple files uploaded by a single user, the queue system should also work across multiple users. For example, if several users are concurrently uploading audio files for translation (which can take a while), those files and the translation jobs should be queued up.

The queuing system should also provide a way to query/know where a file is within the queue, or if it is being in-processed, to enable the UI to provide feedback to users about the state of their upload.

There is a potentially related issue for [creating a queue/processing system that performs runs (#482)](https://github.com/defenseunicorns/leapfrogai/issues/482)

**Comment by jalling97** [comment]
Completed by #942
