### ISSUE TITLE
chore(ui): fix e2es with new lf api

### ISSUE THREAD

**Issue by andrewrisse** [defenseunicorns/leapfrogai#638]
Now that we are using LF API, we don't need to worry about request limiting from OpenAI causing our E2Es to fail. We haven't been able to check that all of these are working again lately, so ensure they are all working.

Also refactor test setups and cleanups to avoid tests being flaky and affecting each other if they run setup/cleanup commands at the same time and affect each other.

**Comment by justinthelaw** [comment]
Bumping for new EPIC around `Made for UDS`: https://github.com/defenseunicorns/uds-common/blob/main/docs/uds-package-practices.md#testing

**Comment by andrewrisse** [comment]
closed by #713
