### ISSUE TITLE
feat(api): Ensure chunk metadata is being stored in the DB

### ISSUE THREAD

**Issue by gphorvath** [defenseunicorns/leapfrogai#665]
### User Story

**As a** user
**I want** annotations
**So that** know what part of the file was use

### Acceptance Criteria

**Given** [a state]  
**When** [an action is taken]  
**Then** [something happens]

### Additional context
To accomplish this we need to ensure the chunk metadata is saved in the data for later use.

**Comment by andrewrisse** [comment]
@gphorvath Is this part of #766 and should it be a standlone story? or can we close it as a dup

**Comment by gregclark-defenseunicorns** [comment]
Closing. If there is something that needs to be in the DB then open a new issue
