### ISSUE TITLE
Unable to perform text-embeddings on files larger than 16MB with our file upload

### ISSUE THREAD

**Issue by YrrepNoj** [defenseunicorns/leapfrogai#666]
When uploading large-ish PDFs we run into an error in our API with a message along the lines of `Received message larger than. max`. Figure out why we are getting this error and fix!

<img width="1595" alt="Screenshot 2024-06-18 at 3 18 46 PM" src="https://github.com/defenseunicorns/leapfrogai/assets/18587823/d6d46ffc-76db-4733-8fc0-9a6a78f010bb">

**Comment by CollectiveUnicorn** [comment]
Should be resolved by #746
