### ISSUE TITLE
Assistant repeating itself and being confused by control messages input from the user

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/leapfrogai#683]
### Environment
Device and OS: pop OS 22.04
App/package versions: 0.8.0
Kubernetes distro being used: N/A
Other: N/A

### Steps to reproduce

1. Interact somewhat erratically with the assistant using `USER`, `ASSISTANT` and `/s` text.

### Expected result

The assistant is able to carry on and doesn't get confused as to who is speaking.

### Actual Result

The assistant gets confused and starts repeating itself.

### Visual Proof (screenshots, videos, text, etc)

![image](https://github.com/defenseunicorns/leapfrogai/assets/3977569/8e7ec0f7-e0c8-4686-a643-8dae59cb1877)

### Severity/Priority

Medium

### Additional Context

The thread IDs in the staging test instance are: `fdddc6c3-269c-4c0c-b7b0-06d3553303f0` and `75b6f390-ba9e-44ac-a0e3-ae9641bd9908`

**Comment by justinthelaw** [comment]
@andrewrisse @YrrepNoj do you think we should strip the special tokens using the some of the upstream HuggingFace configuration and [generation](https://huggingface.co/migtissera/SynthIA-7B-v1.3/blob/main/special_tokens_map.json) files? The stripping can probably happen at the API and/or UI backend level, but I'll leave the architecture up to you guys and team discussion.

Example upstream file for special tokens: https://huggingface.co/migtissera/SynthIA-7B-v1.3/blob/main/special_tokens_map.json

This also opens the longer discussion of taking in more from the HF configurations programatically, or at least forcing a user to declaratively input them in our configuration YAML: https://huggingface.co/migtissera/SynthIA-7B-v1.3/tree/main (e.g., config.json, generation_config.json, tokenizer_config.json, etc.). Note that not all repos have all configuration files, so the latter is probably the best approach.

**Comment by andrewrisse** [comment]
I'd prefer to strip them on the backend for now so we can still run against OpenAI normally. Backend can remove that workaround once handled properly.

**Comment by joelmccoy** [comment]
Unsure if related (but I noticed in this chat screenshot)... I am getting an extra newline special token at the end of a response: 
![image](https://github.com/user-attachments/assets/4dc37952-9f9a-4056-b486-c03eb7822c78)
Conversation id 8739f827-73aa-420d-90bb-556e97a978fe in staging.

**Comment by gphorvath** [comment]
Closing this for now. We recommend not trying to confuse the LLM - also as we move to newer models, the LLM should be more robust in it's responses.

If you continue to see an unsolicited `\n` in the responses, please open a specific bug for that @joelmccoy and we'll look into it further!
