### ISSUE TITLE
feat(ui) Chat Page UI enhancements

### ISSUE THREAD

**Issue by gregclark-defenseunicorns** [defenseunicorns/leapfrogai#690]
### User Story

**As a** LFAI
**I want** UI enhancements
**So that** I have a better experience using LFAI

### Acceptance Criteria
**Chat Page**

- [x] Persist error notifications until closed manually `Design: Chat`
- [x] Move + icon on New Chat button to right of button and text to left and icon to right `Design: Chat`
- [x] Reduce left padding in left panel for both the menu and submenu items. Ideally all the Button text (New Chat, Import..., Export...) and menu item text all align down the panel and then the submenu item text is indented 1rem (16px) from that. `Design: Chat`
- [x] Remove top padding between the menu item text and associated submenu text. Leave the bottom padding `Design: Chat`
- [x] Only show 3 dot menu on chat thread list on hover `Design: Chat - 3 Dot Menu`
- [x] Can we move the 3 dot menu into the button instead of to the right? `Design: Chat - 3 Dot Menu`
- [x] Change 3 dot menu style to look like a dropdown list `Design: Chat - 3 Dot Menu`
- [x] Change Import/Export chat history buttons to "Alternate" style `Design: Chat`
- [x] Move Assistant drop down to left of Prompt message input field `Design: Chat`
- [x] Change style of assistant drop down to match prompt input (Does the input have an outline by default?) `Design: Chat`
- [x] Change Assistant dropdown menu to match Figma design `Design: Chat - Assistants Dropdown`
- [x] Change the "None" selection to "No Assistant" `Design: Chat - Assistants Dropdown`
- [x] Change send icon in prompt input to be an up arrow `Design: Chat`
- [x] Change color of file and send icon in prompt input to match place holder text (gray-400) `Design: Chat`
- [x] Create hover color of file and send icon in prompt input and set to gray-300
- [ ] Change Code Block header background to gray-600 `Design: Chat - Code Blocks`
- [ ] Change Code Block body background to gray-800 `Design: Chat - Code Blocks`
- [ ] Change Code Block border to gray-600 `Design: Chat - Code Blocks`
- [ ] Change Delete Chat modal to match Figma design (Should be a [Pop-Up](https://flowbite-svelte.com/docs/components/modal#Pop-up_modal) modal in Flowbite) `Design: Chat - Toasts/Modals`
- [ ] Change Importing chat history toast to say just "Importing Chat History..." with spinner. See Figma design) `Design: Chat - Toasts/Modals`
- [ ] Add "Chat History imported successfully." toast when successful import `Design: Chat - Toasts/Modals`
- [ ] Add "Chat History import failed." toast when import fails `Design: Chat - Toasts/Modals`
- [ ] Add "Chat History exported successfully." toast when successful export `Design: Chat - Toasts/Modals`
- [ ] Add "Chat History export failed." toast when export fails `Design: Chat - Toasts/Modals`
- [ ] Add success toast when Chat thread is deleted successfully `Design: Chat - Toasts/Modals`
- [ ] Update spacing in top and bottom sections in left panel to be 16px on top and bottom and 12px on the left and right `Design: Chat`

### Attachments
Design Links:
- [Chat](https://www.figma.com/design/Vaw2TCF9DPAp1msj5TWkl0/Leapfrog-AI?node-id=4165-220254&m=dev&t=KcSE4TpxCwygPP4O-1)
- [Chat - 3 Dot Menu](https://www.figma.com/design/Vaw2TCF9DPAp1msj5TWkl0/Leapfrog-AI?node-id=4237-89259&m=dev&t=KcSE4TpxCwygPP4O-1)
- [Chat - Assistants Dropdown](https://www.figma.com/design/Vaw2TCF9DPAp1msj5TWkl0/Leapfrog-AI?node-id=4252-12702&m=dev&t=KcSE4TpxCwygPP4O-1)
- [Chat - Code Blocks](https://www.figma.com/design/Vaw2TCF9DPAp1msj5TWkl0/Leapfrog-AI?node-id=4335-254448&m=dev&t=KcSE4TpxCwygPP4O-1)
- [Chat - Toasts/Modals](https://www.figma.com/design/Vaw2TCF9DPAp1msj5TWkl0/Leapfrog-AI?node-id=4335-259924&m=dev&t=KcSE4TpxCwygPP4O-1)

**Comment by andrewrisse** [comment]
See #1168 for changes that completed about half of the items
