### ISSUE TITLE
chore(deps): ensure a dependency workflow checks all upstream resources and dependencies

### ISSUE THREAD

**Issue by gphorvath** [defenseunicorns/leapfrogai#696]
### Describe what should be investigated or refactored

* Make sure Zarf packages, UDS bundles, etc. are actually tracked by the bot and automatically open PRs. If Dependabot doesn't support this, then checkout Renovate.

### Links to any relevant code
https://github.com/defenseunicorns/uds-common/blob/main/docs/uds-package-practices.md

### Additional context
Add any other context or screenshots about the technical debt here.

**Comment by justinthelaw** [comment]
Example renovate config: https://github.com/defenseunicorns/uds-common/blob/main/config/renovate.json5
