### ISSUE TITLE
(spike) Create a Custom RAG Evaluations Dataset

### ISSUE THREAD

**Issue by jalling97** [defenseunicorns/leapfrogai#716]
## Description
In order to develop mission-focused evaluations, a custom RAG evaluations dataset is necessary. This dataset should be based on RAG tasks that are representative of current use cases. 

## Completion Criteria
- [x] Identify sources of data that are representative of current use case scenarios. 
- [x] Build a [dataset](https://docs.confident-ai.com/docs/evaluation-datasets) using this ground truth data.
- [x] Build a draft dataset to be used for [Needle in a Haystack](https://arize.com/blog-course/the-needle-in-a-haystack-test-evaluating-the-performance-of-llm-rag-systems/) evaluations.
- [x] Refine the dataset with multiple reviewers (focusing on different perspectives of needs)

## Relevant Links
Consider using [DeepEval Synthesizer](https://docs.confident-ai.com/docs/evaluation-datasets-synthetic-data#1-generating-from-documents) to generate a first draft of the dataset automatically.

**Comment by alekst23** [comment]
It may be difficult to obtain a sufficiently large data set that is "mission specific". However, this is not strictly necessary for doing EVALs. 

There are data sets available like this: https://www.nature.com/articles/s41597-023-02068-4
> Abstract
The BioASQ question answering (QA) benchmark dataset contains questions in English, along with golden standard (reference) answers and related material. The dataset has been designed to reflect real information needs of biomedical experts and is therefore more realistic and challenging than most existing datasets. Furthermore, unlike most previous QA benchmarks that contain only exact answers, the BioASQ-QA dataset also includes ideal answers (in effect summaries), which are particularly useful for research on multi-document summarization.

**Comment by jalling97** [comment]
Current draft dataset: https://huggingface.co/datasets/jalling/LFAI_RAG_qa_v1

**Comment by jalling97** [comment]
Current draft niah dataset: https://huggingface.co/datasets/jalling/LFAI_RAG_niah_v1
