### ISSUE TITLE
feat(api): Chat with existing files while indexing new files

### ISSUE THREAD

**Issue by CollectiveUnicorn** [defenseunicorns/leapfrogai#789]
### User Story

**As the** LeapfrogAI UI
**I want** to chat with existing documents while new documents are indexing
**So that** the user does not have to wait for the new docs to be added before being able to continue their work

### Acceptance Criteria

**Given** there is a vector store with existing documents tied to an assistant
**When** new documents are added and indexed
**Then** the user can still chat with their existing document via the `runs` endpoint without waiting for the indexing of the new files to finish

**Comment by andrewrisse** [comment]
once #885 is merged, we can test to see if this is still an issue

**Comment by CollectiveUnicorn** [comment]
> once #885 is merged, we can test to see if this is still an issue

Unfortunately, it seems like this is still an issue.
