### ISSUE TITLE
chore(api): Do not block when creating/updating VectorStores or Assistants

### ISSUE THREAD

**Issue by CollectiveUnicorn** [defenseunicorns/leapfrogai#803]
### Describe what should be investigated or refactored
When hitting the endpoint to create or update VectorStores/Assistants there is a blocking operation that occurs with the indexing service. The implementation needs to be updated so that the indexing is run as a background job so that the user is not blocked waiting for the indexing to finish before being able to use an assistant.

### Additional context
[FastAPI background tasks](https://fastapi.tiangolo.com/tutorial/background-tasks/) are one way to do this. Indexing status is required before this can be done, as otherwise the frontend will be unable to determine when indexing has completed.

**Comment by CollectiveUnicorn** [comment]
Blocked by https://github.com/defenseunicorns/leapfrogai/issues/788

**Comment by YrrepNoj** [comment]
#885 might mitigate some of this issue.

It appears like our API and EmbeddingsModel was in a fail loop which was causing a single request to repeat multiple times. After #885 the core issue described by this issue might be mitigated.

That said, I believe this issue should stay open. #885 might make this less painful, but it is still a painful thing that we should address.

**Comment by CollectiveUnicorn** [comment]
Confirming that this still seems to be an issue post #885 unfortunately
