### ISSUE TITLE
chore(release): Tag current releases as `-upstream` flavor

### ISSUE THREAD

**Issue by barronstone** [defenseunicorns/leapfrogai#804]
### Describe what should be investigated or refactored
Update our release process to tag our current releases as `-upstream`, similar to how this [UDS Core package's](https://github.com/defenseunicorns/uds-core/pkgs/container/packages%2Fuds%2Fcore/243106403?tag=0.24.0-upstream) tag includes `-upstream`.

### Links to any relevant code
Related issues for the creating the `registry1` flavor:
- https://github.com/defenseunicorns/leapfrogai/issues/704
- https://github.com/defenseunicorns/leapfrogai/issues/730
- https://github.com/defenseunicorns/leapfrogai/issues/736

### Additional context
These tags are used by the security hub to find different flavors of packages. As we eventually build out other `registry1` and `unicorn` flavors, we will need to tag our releases accordingly and include those "flavors" in the Zarf files.

**Comment by CollectiveUnicorn** [comment]
Blocked by #750
