### ISSUE TITLE
Assistant File Upload blends with prompting making it difficult to distinguish where upload new file is

### ISSUE THREAD

**Issue by unicorn-kp** [defenseunicorns/leapfrogai#841]
### Environment
Burning Boats

### Steps to reproduce
1. New assistant, go select files.

### Expected result
Clearly deleniated "Upload File" area

### Actual Result
Upload file is in the same background and font as the prompt area so it blends in. I actually thought I had encountered a bug and the upload files button was gone and I've been working in leapfrog for a while.

### Visual Proof (screenshots, videos, text, etc)
![image](https://github.com/user-attachments/assets/f6425326-83c2-4b15-90ed-cbe2eeb78467)

### Severity/Priority
Low/Nice to Have

**Comment by andrewrisse** [comment]
no longer an issue with flowbite re-design
