### ISSUE TITLE
bug(api, ui): Auth endpoints spammed with refresh token requests prevents API functions

### ISSUE THREAD

**Issue by CollectiveUnicorn** [defenseunicorns/leapfrogai#843]
### Steps to reproduce
1. Run the assistant playwright tests a bunch of times

### Expected result
1. The tests runs to completion

### Actual Result
1. Auth errors are spammed in the kong pod and the API ceases to function

### Visual Proof (screenshots, videos, text, etc)
![Screenshot 2024-07-26 at 2 58 29 PM](https://github.com/user-attachments/assets/78f386ee-6805-48ae-83b2-f167841077e7)

### Severity/Priority
High

### Additional Context
This has been seen in multiple environments and the specific cause is unclear. Restarting `kong` seems to fix the issue.

**Comment by unicorn-kp** [comment]
Here's what I did:

1. Open new assistant
2. Add 4 pdfs, 1 docx
3. Total page length ~100 pages
4. Total size : ~1.8 MB
5. Click save

Assistants says processing but hangs

Everything else crashes.

**Comment by CollectiveUnicorn** [comment]
The default Suapbase rate limiting might be affecting this: https://github.com/supabase/supabase/blob/9d5d4626ef8791e011a7c9a8912ba7a870f7d58e/packages/shared-data/config.ts#L46

**Comment by andrewrisse** [comment]
test this after merging of #885

**Comment by gregclark-defenseunicorns** [comment]
@andrewrisse Feel free to test this and close

**Comment by YrrepNoj** [comment]
We believe #885 has resolved this issue and will reopen if we notice it in the future.
