### ISSUE TITLE
bug(ui): ui shows some html entities in code blocks

### ISSUE THREAD

**Issue by hbeaster** [defenseunicorns/leapfrogai#853]
### Environment
Device and OS: Desktop Windows
App/package versions: unsure
Kubernetes distro being used: unsure
Other:

### Steps to reproduce
1. Ask "Create a c# function that returns a func"
2. Observe the code block
3. Observe the lambda function's arrow ">" 

### Expected result
The ">" should be ">"

### Actual Result
The ">" is actually "&gt"

### Visual Proof (screenshots, videos, text, etc)
![image](https://github.com/user-attachments/assets/a15c1498-05dd-405d-af8e-024b5e917c22)

### Severity/Priority
Low

### Additional Context
N/A

**Comment by andrewrisse** [comment]
@justinthelaw I think this may have been fixed by #1006 
I inputted that same prompt and got the '>'
It is possible the LLM could return something weird though that gets rendered incorrectly.
how do you feel about closing this?

**Comment by justinthelaw** [comment]
Yes, I haven't seen this issue since 0.12.2, so it must be gone!
