### ISSUE TITLE
bug: vllm bundle has invalid kubernetes spec and won't properly deploy on internal infrastructure

### ISSUE THREAD

**Issue by joelmccoy** [defenseunicorns/leapfrogai#965]
### Environment

1. OS and Architecture: RHEL8 Kubernetes on rke2
2. App or Package Name: vllm
2. App or Package Version: 0.11.0
3. Kubernetes Distribution: rke2
4. Kubernetes Version: rke2 1.28.12
6. Other: This bug is showing up in our internal Defense Unicorns Infrastructure

### Steps to reproduce

1. Deploy vllm bundle 0.11.0

### Expected result
vllm zarf package should deploy successfully
-

### Actual Result
zarf deployment hangs and is unable to create the data injection target
-

### Visual Proof (screenshots, videos, text, etc)
![image](https://github.com/user-attachments/assets/1a9f1960-e736-442c-9e05-9fa611672985)
```
W0829 00:07:19.536249     407 warnings.go:70] unknown field "spec.template.spec.containers[0].securityContext.fsGroup"
W0829 00:07:19.536261     407 warnings.go:70] unknown field "spec.template.spec.initContainers[0].securityContext.fsGroup"
  •  Processing helm chart vllm-model:0.11.0 from Zarf-generated helm chart
 NOTE  Using config file
mkdir: can't create directory '/data/.model': Permission denied
command terminated with exit code 1
 WARNING  Unable to create the data injection target directory /data/.model in pod
 vllm-model-5c99c4fc68-xpql5
 NOTE  Using config file
mkdir: can't create directory '/data/.model': Permission denied
command terminated with exit code 1
 WARNING  Unable to create the data injection target directory /data/.model in pod
 vllm-model-5c99c4fc68-xpql5
```

### Additional Context

There is actually an invalid kubernetes manifest spec that may be causing this.  Defining fsGroup under initContainers or containers is not valid, and therefore that may be the issue creating this directory.  Instead, fsGroup should be defined at the spec.template.spec.securityContext level, not within the containers/initContainers array.
Improper definitions can be found [here](https://github.com/defenseunicorns/leapfrogai/blob/v0.11.0/packages/vllm/chart/values.yaml#L26), [here](https://github.com/defenseunicorns/leapfrogai/blob/v0.11.0/packages/vllm/chart/templates/deployment.yaml#L37) and [here](https://github.com/defenseunicorns/leapfrogai/blob/v0.11.0/packages/vllm/chart/templates/deployment.yaml#L64).

**Comment by justinthelaw** [comment]
PR #937 is a WIP that will solve the manifest warning issues.

The data injection issue is a known issue that only occurs in environments that don't use `local-path` (or variants like LPP) as the `StorageClass`, and is not related to the manifest warnings.

A recommended fix, separate from PR #937, to the actual issue you are encountering is to mount the volume to a directory that has had its permissions changed in the Docker manifest OR to provide root to the `initContainer`. cc: @YrrepNoj @CollectiveUnicorn

**Comment by justinthelaw** [comment]
For now, please rollback to 0.9.2. I think I need to discuss with the team at stand-up later today on the solution, as the best place to test the solution is on our staging environment that uses EFS (which I don't currently have access to). I've also been out for a little bit, so they may already have thought about or completed the fix!

**Comment by joelmccoy** [comment]
> as the best place to test the solution is on our staging environment that uses EFS (which I don't currently have access to).

I'd also be happy to get you and anyone else setup in this environment

**Comment by joelmccoy** [comment]
related: https://github.com/zarf-dev/zarf/issues/2263

I'm not sure there is a known work around for using zarf data injection as a nonroot user :/
